### PR TITLE
Export az afd api with aaz

### PR DESCRIPTION
**Pull request by Ptnan7**

### CODE REVIEW

**Comment by kairu-ms** [comment]
@Ptnan7 Could you add link of any PR in azure-cli or azure-cli-extensions?

**Comment by kairu-ms** [comment]
https://github.com/Azure/azure-cli/pull/27807

**Comment by necusjz** [comment]
Seems all the afd commands should be in preview not "Stable" https://github.com/Azure/azure-cli/blob/71d478f3df9dbc6fe8583baf9308a7597450011f/src/azure-cli/azure/cli/command_modules/cdn/commands.py#L289.

**Review by necusjz — CHANGES_REQUESTED** [review]
And the current PR is not "clean" enough, please pull the latest <main> branch, and <Export> your command model again.

**Pull request closed without merging**
