### PR TITLE
[cdrp] add `compute-sku-recommender` command group

### PR DESCRIPTION
**Pull request by joal42**
- Add `compute-sku-recommender` command group for spot placement cli 
- cli pr: https://github.com/Azure/azure-cli/pull/28750

### CODE REVIEW

**Comment by kairu-ms** [comment]
@joal42, please attach the cli PR link.

**Comment by joal42** [comment]
> @joal42, please attach the cli PR link.

https://github.com/Azure/azure-cli/pull/28750

**Comment by kairu-ms** [comment]
Please help resolve conflicts.

**Comment by joal42** [comment]
> Please help resolve conflicts.

Done.

**Review by necusjz — APPROVED** [review]

**Pull request merged**
